# Generated by Django 5.2.4 on 2025-08-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('git_url', models.URLField()),
                ('default_branch', models.CharField(default='master', max_length=100)),
                ('current_branch', models.CharField(blank=True, max_length=100)),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NotCloned', 'NotCloned'), ('UpToDate', 'UpToDate'), ('Modified', 'Modified'), ('Behind', 'Behind')], default='NotCloned', max_length=20)),
                ('auto_clone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
