# Generated by Django 5.2.4 on 2025-08-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_paths', models.JSONField(default=dict)),
                ('projects_root', models.CharField(max_length=255)),
                ('rsync_groups', models.JSONField(default=dict)),
                ('output_root', models.CharField(max_length=255)),
                ('ssh_keys', models.JSONField(default=list)),
                ('log_directory', models.CharField(max_length=255)),
            ],
        ),
    ]
